# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78e50ba33925900c6e1c1dc7941c39bc16a9813e02935c6b4e36be87977484503ed6a82d71d8bdc0fb5550e3a6a28450772b8908949cc651bc2c4e812d9296ea

test:
  secret_key_base: 1abb100999f5c1da44b76c708e383ea0da65d78278d7d750aa7046b4d713a0e8899c2f75e9afdf8bc843db76900a263a1fe3277367db15a9488aabd162df527c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
