# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Role.create(name: "Superadmin")
# Role.create(name: "Student")
# Role.create(name: "Employee")
# Role.create(name: "Co-Admin")
#User.create(f_name: "Admin", email: "abcd@gmail.com" , password: "123456")
# Subject.create(name: "Hindi")
# Subject.create(name: "English")
# Subject.create(name: "Maths")
# Subject.create(name: "Social")
# Subject.create(name: "Science")
# Subject.create(name: "Computers")
# Subject.create(name: "General Knowledge")
SClass.create(name: 'Nursery')
SClass.create(name: 'Play Group')
SClass.create(name: 'LKG')
SClass.create(name: 'UKG')
SClass.create(name: '1')
SClass.create(name: '2')
SClass.create(name: '3')
SClass.create(name: '4')
SClass.create(name: '5')
SClass.create(name: '6')
SClass.create(name: '7')
SClass.create(name: '8')
SClass.create(name: '9')
SClass.create(name: '10')
SClass.create(name: '11')
SClass.create(name: '12')

